# Generated by Django 5.1.3 on 2024-12-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("roll", models.CharField(max_length=15)),
                ("subject", models.CharField(max_length=200)),
                ("mark", models.IntegerField()),
            ],
        ),
    ]
